services:
  postgres:
    image: postgres:15-alpine
    environment:
      POSTGRES_DB: video_balancer
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
    ports:
      - "5434:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 10s
      timeout: 5s
      retries: 5

  app:
    build: .
    ports:
      - "8000:8000"
    environment:
      DATABASE_URL: postgresql+asyncpg://postgres:password@postgres:5432/video_balancer
      CDN_HOST: cdn.example.com
      DEFAULT_CDN_RATIO: 9
      DEFAULT_ORIGIN_RATIO: 1
    depends_on:
      postgres:
        condition: service_healthy
    command: uvicorn src.app.main:app --host 0.0.0.0 --port 8000 --reload

volumes:
  postgres_data:



